[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \..*|  # hidden directories
    build|
    dist|
    .venv|
    venv|
    __pycache__|
    .git|
    .mypy_cache|
    .pytest_cache|
    .tox|
    .eggs|
    .github
)/
'''

[tool.isort]
profile = "black"
