
name: Update Manifest and Changelog on PR

permissions:
  contents: write
  issues: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - custom_components/nissan_na/manifest.json

jobs:
    update-files:
      runs-on: ubuntu-latest
      if: ${{ !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]') }}
      steps:
      # Decode the GitHub App Private Key
      - name: Decode the GitHub App Private Key
        id: decode
        run: |
          private_key=$(echo "${{ secrets.ACTIONS_RUNNER_APPLICATION_PRIVATE_KEY }}" | base64 -d | awk 'BEGIN {ORS="\\n"} {print}' | head -c -2) &> /dev/null
          echo "::add-mask::$private_key"
          echo "private-key=$private_key" >> "$GITHUB_OUTPUT"

      # Get workflow token
      - name: Get Token
        id: get_workflow_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.ACTIONS_RUNNER_APPLICATION_ID }}
          private-key: ${{ steps.decode.outputs.private-key }}

      # Get GitHub App User ID
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.get_workflow_token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.get_workflow_token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.get_workflow_token.outputs.app-slug }}[bot]@users.noreply.github.com'

      # Checkout code
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0 # This ensures all tags and history are fetched

      # Fix permissions
      - name: Fix permissions (no sudo)
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          chmod -R u+rw .

      # Determine next pre-release version
      - name: Get next pre-release version
        id: next_version
        run: |
          VERSION=$(git tag --list 'v*' | sed 's/^v//' | sort -V | tail -n 1)
          if [ -z "$VERSION" ]; then
            VERSION="0.0.0"
          fi
          NEXT_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1; print $0}' OFS=.)
          echo "next_version=${NEXT_VERSION}" >> $GITHUB_OUTPUT

      # Update manifest.json version to pre-release
      - name: Update manifest.json version
        run: |
          jq '.version = "${{ steps.next_version.outputs.next_version }}"' custom_components/nissan_na/manifest.json > tmp.$$.json && mv tmp.$$.json custom_components/nissan_na/manifest.json

      # Generate and update CHANGELOG.md
      - name: Update CHANGELOG.md
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: .github/changelog-configuration.json
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          version: ${{ steps.next_version.outputs.next_version }}

      # Commit and push changes to PR branch
      - name: Commit and push changes
        run: |
          git add CHANGELOG.md custom_components/nissan_na/manifest.json
          git commit -m "docs: update CHANGELOG.md and manifest.json version for ${{ steps.next_version.outputs.next_version }} [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}

      # Create pre-release tag
      - name: Create pre-release tag
        run: |
          git tag v${{ steps.next_version.outputs.next_version }}
          git push origin v${{ steps.next_version.outputs.next_version }}

      # Create GitHub Pre-release
      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.next_version.outputs.next_version }}
          name: Pre-release v${{ steps.next_version.outputs.next_version }}
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}